### PR TITLE
Update mat sim

### PR DESCRIPTION
**Pull request by tschlenther**

### CODE REVIEW

**Comment by tschlenther** [comment]
also set the version number to 2024.2

**Comment by tschlenther** [comment]
for some reason, now the `.avro` files generated for the `AverageKelheimNoiseDashboard` are almost empty... I had update change the `avro` dependency to stay up to date with the version in `matsim-libs`...
@simei94 can you see any other reason why this suddenly doesn't work, anymore? The test also fails...

**Comment by tschlenther** [comment]
no. it's broken here, but works on the master. see the test results. BTW: maybe the test could use a few more comments, e.g. why do we assume the value 2 everywhere?

**Comment by simei94** [comment]
@tschlenther the NoiseAverageAnalysis now works again. It was due to a object / datatype change in .avro files from GenericData arrays to PrimitivesArrays, both part of the apache avro package. The package must have been updated in matsim-libs and therefore it did not work after the matsim version update

**Pull request merged**
