### PR TITLE
Adding congestion analysis

### PR DESCRIPTION
**Pull request by luchengqi7**
The traffic analysis script will produce the following useful data:
1. A single congestion index for the whole network (within the optinal shape file) --> This can be useful for the Dusseldorf scenario also!!!
2. Congestion index and average speed ratio for all the links (within the optinal shape file) in the network 
3. Average speed ratio of the whole netowork (within the optinal shape file) throughout the day (15-mintues interval)
4. Detailed statisctics for further analysis and plotting. 

Difference to the LinkStat: The time interval is adjustable. Congestion index is provided.

Further improvments:
Enable input of selected links (e.g. only include major roads and do not include the smaller roads)

### CODE REVIEW

**Comment by luchengqi7** [comment]
image

We can also plot something like that (x axis is the time of the day, here 1 time bin = 15min). And plot 2 lines in the same plot: one is before and one is after.

**Comment by rakow** [comment]
How does the output csv look like ? Can you past a few lines, thx.

**Comment by luchengqi7** [comment]
[traffic.csv](https://github.com/matsim-scenarios/matsim-kelheim/files/7499832/traffic.csv)
After removeing the link with daily traffic count below 1000 (this value is configurable through command line), the new traffic analysis is as shown in this csv file, which is much eaiser to read.

@rakow Do you think it will also be a good idea to add another filter that intake a list of links (e.g. csv file with Link IDs string) to be considered? (e.g. major roads in the city)

**Comment by luchengqi7** [comment]
image
It seems the traffic pattern is a little bit weird in Kelheim 😅

**Comment by kt86** [comment]
Hi @luchengqi7,
just saw it in my mailbox -> Sorry for jumping in here.
I am not 100% sure if this is also valid here, but I think we decided (at the PhD Student seminar??), that we try to use *.tsv instead of *.csv. 

This does not mean, changing existing outputs immediately. But when creating a new one, this is most likely the preferred way to go.
The reason was that we avoid the trouble with the separator ("," or ";" and problems with decimal number in German/English format).

Best, 
Kai MT

**Comment by luchengqi7** [comment]
> Hi @luchengqi7, just saw it in my mailbox -> Sorry for jumping in here. I am not 100% sure if this is also valid here, but I think we decided (at the PhD Student seminar??), that we try to use *.tsv instead of *.csv.
> 
> This does not mean, changing existing outputs immediately. But when creating a new one, this is most likely the preferred way to go. The reason was that we avoid the trouble with the separator ("," or ";" and problems with decimal number in German/English format).
> 
> Best, Kai MT

Oh, I thought we made an agreement that we will use CSV file as the standard format... And use "," as the standard division... And therefore I have been using CSV file since then...🙈

**Comment by luchengqi7** [comment]
[traffic.csv](https://github.com/matsim-scenarios/matsim-kelheim/files/7505668/traffic.csv)
@kt86 So I have updated the "CsvWriter" format to "TDF", which means it use Tab as the delimiter now. I guess this is the file type we want? 

(Github does not support .tsv so I use .csv as the ending in the attached file. But the delimiter is now Tab...)

**Review by rakow — APPROVED** [review]

**Pull request merged**
